#!/usr/bin/env python3
"""Merge `translation/profiles_ko.tsv` into the `ko` column of the worklist.

The worklist (`survey/common/file30_profiles.tsv`) is machine-generated by
extract_profiles, so a regeneration would wipe hand-written Korean. Keeping the
translations in their own offset-keyed file and merging them back means the
worklist can be rebuilt at any time without losing work.

    python tools/merge_profiles.py
"""
import os, sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(BASE, "translation", "profiles_ko.tsv")
DST = os.path.join(BASE, "survey", "common", "file30_profiles.tsv")


def main():
    ko = {}
    for ln in open(SRC, encoding="utf-8").read().splitlines()[1:]:
        f = ln.split("\t")
        if len(f) >= 2 and f[1].strip():
            ko[f[0].strip().upper()] = f[1]

    lines = open(DST, encoding="utf-8").read().splitlines()
    out, filled, kept = [lines[0]], 0, 0
    for ln in lines[1:]:
        f = ln.split("\t")
        while len(f) < 6:
            f.append("")
        k = f[0].strip().upper()
        if k in ko:
            if f[5].strip() and f[5] != ko[k]:
                kept += 1        # the worklist already carries a different one
            f[5] = ko[k]
            filled += 1
        out.append("\t".join(f))
    open(DST, "w", encoding="utf-8", newline="").write("\n".join(out) + "\n")

    unknown = ko.keys() - {l.split("\t")[0].strip().upper() for l in lines[1:]}
    print(f"merged {filled} translations ({kept} overwrote an older one)")
    if unknown:
        print(f"  !! {len(unknown)} offsets not in the worklist: "
              f"{sorted(unknown)[:5]}")


if __name__ == "__main__":
    main()
